// This file is generated by zbuild. Do not edit manually.

const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const options_build_options = b.addOptions();
    const option_napi_version = b.option([]const u8, "napi_version", "") orelse "10";
    options_build_options.addOption([]const u8, "napi_version", option_napi_version);
    const options_module_build_options = options_build_options.createModule();

    const module_zapi = b.createModule(.{
        .root_source_file = b.path("src/root.zig"),
        .target = target,
        .optimize = optimize,
    });
    module_zapi.addIncludePath(b.path("include"));
    b.modules.put(b.dupe("zapi"), module_zapi) catch @panic("OOM");
    b.modules.put(b.dupe("napi"), module_zapi) catch @panic("OOM");

    module_zapi.addImport("build_options", options_module_build_options);

    const test_zapi = b.addTest(.{
        .name = "zapi",
        .root_module = module_zapi,
    });
    const run_test = b.addRunArtifact(test_zapi);
    const tls_test = b.step("test", "Run all tests");
    tls_test.dependOn(&run_test.step);

    buildExamples(b, target, optimize, module_zapi);
}

pub fn buildExamples(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.builtin.OptimizeMode, napi: *std.Build.Module) void {
    // Build all examples from examples/<name>/mod.zig
    const tls_build_examples = b.step("examples", "Build all examples");

    var examples_dir = std.fs.openDirAbsolute(b.pathFromRoot("examples"), .{ .iterate = true }) catch |err| {
        std.debug.print("Warning: could not open examples directory: {}\n", .{err});
        return;
    };
    defer examples_dir.close();

    var it = examples_dir.iterate();
    while (it.next() catch @panic("Failed to iterate examples directory")) |entry| {
        if (entry.kind != .directory) continue;
        const name = b.dupe(entry.name);

        const mod = b.createModule(.{
            .root_source_file = b.path(b.fmt("examples/{s}/mod.zig", .{name})),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        });
        mod.addImport("zapi", napi);
        mod.addImport("napi", napi);

        const lib = b.addLibrary(.{
            .name = name,
            .root_module = mod,
            .linkage = .dynamic,
        });
        lib.linker_allow_shlib_undefined = true;

        const install_lib = b.addInstallArtifact(lib, .{
            .dest_sub_path = b.fmt("{s}.node", .{name}),
        });

        const tls_build_example = b.step(
            b.fmt("build:examples:{s}", .{name}),
            b.fmt("Build the {s} example", .{name}),
        );
        tls_build_example.dependOn(&install_lib.step);
        tls_build_examples.dependOn(&install_lib.step);
    }
}
